# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'karupasu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for karupasu
  pod 'R.swift'
  pod 'RxSwift', '~> 6.1'
  pod 'RxCocoa', '~> 6.1'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwifterSwift'
  pod "Unio", :git => 'https://github.com/cats-oss/Unio.git'
end
